language: node_js
node_js:
  - stable

before_script:
  - npm install -g bower
script: bash ./deploy/deploy.sh

env:
  global:
  - ENCRYPTION_LABEL: "9c9ce64c70c0"
  - COMMIT_AUTHOR_EMAIL: "ucilug-travisci@zhaofeng.li"

